name:                MachineLearning
version:             0.1.0.0
github:              "Nissen96/haskell-machine-learning"
license:             BSD3
author:              "Alexander F. Nissen, Jacob V. M. Nielsen"
maintainer:          "alexander@feldbech.dk"
copyright:           "2019 - Alexander F. Nissen, Jacob V. M. Nielsen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Nissen96/haskell-machine-learning#readme>

dependencies:
- base >= 4.7 && < 5
- set-monad

library:
  source-dirs: src

executables:
  MachineLearning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MachineLearning

tests:
  MachineLearning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MachineLearning
